app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path('', view=views.index, name='index'),
    path('post_blog', view=views.post_blog, name='post_blog'),
    path('post_comment/<int:id>', view=views.post_comment, name='post_comment'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class BlogModel(models.Model):
    id = models.AutoField(primary_key=True)
    blog_content = models.TextField()
    posted_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id


class CommentModel(models.Model):
    blog_id = models.ForeignKey(BlogModel,on_delete=models.CASCADE)
    comment = models.TextField()
    posted_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_id, self.comment

app/views.py
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from app.models import BlogModel, CommentModel
from django.views.decorators.csrf import ensure_csrf_cookie

def index(request):
    blog_list = BlogModel.objects.all()
    return render(request, 'index.html', {
        'blog_list': blog_list,
    })

@api_view(['POST'])
def post_blog(request):
    if request.method == 'POST':
        blog_content = request.POST.get('blog_content')
        if blog_content is not None:
            blog = BlogModel.objects.create(blog_content=blog_content)
            blog.save()
            return redirect('index')

@ensure_csrf_cookie
@api_view(['POST'])
def post_comment(request, id):
    if request.method == 'POST':
        comment = request.POST.get('comment')
        if comment is not None:
            blog = BlogModel.objects.get(id=id)
            post_comment = CommentModel.objects.create(blog_id=blog, comment=comment)
            post_comment.save()
            return redirect('index')
    return render('index')

app/templates/comments.html
<form method='POST' action="{% url "post_blog" %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Blog</label>
      <input type="text" class="form-control" id="exampleInputEmail1" name="blog_content" aria-describedby="emailHelp" placeholder="Blog here">
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
  </form>

app/templates/index.html
<form method="POST" action="{% url "post_blog" %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Blog</label>
      <input type="text" class="form-control" id="exampleInputEmail1" name="blog_content" aria-describedby="emailHelp" placeholder="Blog here">
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
  </form>
  
  {% for blog in blog_list %}
    <div class="blog-content">
      {{ blog.blog_content }}
    </div></br>
  
    <form action="{% url 'post_comment' blog.id %}" method="POST">
        {% csrf_token %}
      <div class="form-group">
        <input type="text" class="form-control" name="comment" aria-describedby="emailHelp" placeholder="Comment this post">
      </div>
      <button type="submit" class="btn btn-primary">Comment</button>
    </form>
  
    Comments:
    {% for comment in blog.commentmodel_set.all %}
      <div class="comment">
        {{ comment.comment }}
      </div></br>
    {% endfor %}
    <hr></br>
  {% endfor %}
  